import './globals.css'
import "bootstrap/dist/css/bootstrap.min.css";
 import { Inter } from 'next/font/google'

import Footer from '@/components/layout/Footer'

import LeftAside from '@/components/layout/LeftAside'
import RightAside from '@/components/layout/RightAside'
import Header from '@/components/layout/Header';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {// Fuction Start

 

  //Fuction return
  return (
      <html lang="en">
        <body className={inter.className}>
        <div className='container  p-0 s_tbdr' >
      <Header/>
      <main container="">
        <div className='row m-0'>
        <LeftAside/>
        {children}
        <RightAside />
        </div>
      </main>
    <Footer />
      </div>
      </body>
      </html>
    )
  }
//Fuction End
